version: '3'


volumes:
  wordpress:
    driver: local
  db_data:
    driver: local

services:
   mysql:
      image: mysql/mysql-cluster:8.0
      volumes:
        - db_data:/var/lib/mysql
        - ./mysql.conf/my.cnf:/etc/my.cnf
        - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      # restart: always
      deploy:
        mode: replicated
        replicas: 2
      command: ndb_mgmd
      environment:
        MYSQL_ROOT_PASSWORD: diamilikku
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: akuganteng
      networks:
        - wordpress_overlay

   wordpress:
      image: wordpress:latest
      volumes:
        - wordpress:/var/www/html
      ports:
        - "8195:80"
      # restart: always
      depends_on:
        - mysql
      deploy:
        mode: replicated
        replicas: 5
      environment:
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_PASSWORD: akuganteng
      networks:
        - wordpress_overlay

networks:
    wordpress_overlay:
        driver: overlay
        external: true