version: '3'


volumes:
  wordpress:
    driver: local
  db_data:
    driver: local

services:
  management1:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndb_mgmd
    networks:
      wordpress_overlay:
        ipv4_address: 192.168.0.9

  ndb1:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    deploy:
        mode: replicated
        replicas: 2
    command: ndbd
    depends_on:
      - "management1"
    networks:
      wordpress_overlay:
       ipv4_address: 192.168.0.10

  ndb2:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      wordpress_overlay:
        ipv4_address: 192.168.0.11

  mysql1:
    image: mysql/mysql-cluster
    ports:
      - "3306:3306"
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    environment:
      MYSQL_ROOT_PASSWORD: akuganteng
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: akuganteng
    command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
    networks:
      wordpress_overlay:
        ipv4_address: 192.168.0.20

  wordpress:
      image: wordpress:latest
      volumes:
        - wordpress:/var/www/html
      ports:
        - "8195:80"
      depends_on:
        - mysql
      deploy:
        mode: replicated
        replicas: 5
      environment:
        WORDPRESS_DB_HOST: mysql1
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_PASSWORD: akuganteng
      networks:
        - wordpress_overlay

networks:
    wordpress_overlay:
        driver: overlay
        external: true